### ISSUE TITLE
How to generate high-quality projected hexahedral mesh

### ISSUE THREAD

**Issue by zyyue99** [cg3hci/Gen-Adapt-Ref-for-Hexmeshing#7]
Hi, could you please tell me how to generate hexahedral meshes of the same quality as those in the paper? I used the command "./make_grid --surface --input_mesh_path=***.obj --output_grid_path=***.mesh --project_mesh=true", but the quality of the projected hexahedral results is not good. Thank you very much.

**Comment by mlivesu** [comment]
We used a third party software to smooth and untangle the projected mesh
(http://www.cs.ubc.ca/labs/imager/tr/2018/HexDemo/)
